
extern BOOL goTopBydeVbugForSafari();
extern BOOL goBottomBydeVbugForSafari();
extern BOOL goLeftBydeVbugForSafari(int);
extern BOOL goRightBydeVbugForSafari(int);
extern BOOL goUpBydeVbugForSafari(int);
extern BOOL goDownBydeVbugForSafari(int);
extern void prevTabBydeVbugForSafari();
extern void nextTabBydeVbugForSafari();
extern BOOL reloadBydeVbugForSafari();
extern void openNewTabBydeVbugForSafari();
extern void closeTabBydeVbugForSafari();
extern void focusAddressViewBydeVbugForSafari();
extern BOOL resignFocusToMainViewBydeVbugForSafari();
extern void showSearchOnThisPageBydeVbugForSafari();
extern void nextSearchOnPageBydeVbugForSafari();
extern void prevSearchOnPageBydeVbugForSafari();
extern BOOL goBackBydeVbugForSafari();
extern BOOL goForwardBydeVbugForSafari();
